// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
  VAPI_API_KEY: string;
  VAPI_ASSISTANT_ID: string;
}
